common_params:
  - &common_plugins
    - automattic/bash-cache#2.2.0
  - &common_env
    IMAGE_ID: xcode-13.4.1

steps:
  - label: "Build and Test"
    command: |
      build_and_test_pod
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "artifacts/**/*"

  - label: "Validate Podspec"
    command: |
      validate_podspec
    env: *common_env
    plugins: *common_plugins
